# Generated by Django 6.0.1 on 2026-02-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Укажите название книги')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Загрузите изображение обложки книги')),
                ('author', models.CharField(max_length=200, verbose_name='Укажите автора книги')),
                ('description', models.TextField(verbose_name='Укажите описание книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Укажите цену книги')),
                ('pages', models.PositiveIntegerField(verbose_name='Укажите количество страниц')),
                ('published_date', models.DateField(verbose_name='Укажите дату публикации')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Загрузите файл книги')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Укажите сайт книги')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Укажите email для связи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
